docker:
  image: yegor256/java8
assets:
  settings.xml: zerocracy/home#assets/zerocracy/settings.xml
  id_rsa: zerocracy/home#assets/heroku-key
  id_rsa.pub: zerocracy/home#assets/heroku-key.pub
  s3cfg: zerocracy/home#assets/s3cfg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |-
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  sudo apt-get update
  sudo apt-get install -y mongodb-org
  sudo gem install pdd
  sudo gem install xcop
  sudo gem install sass -v 3.4.25
  java -version
deploy:
  script: |
    mvn clean install -Prultor --settings ../settings.xml --quiet
    mvn clean --quiet
    pdd --source=$(pwd) --verbose --file=zc-farm.xml
    s3cmd --no-progress put zc-farm.xml --config=../s3cfg s3://pdd.teamed.io/zc-farm.xml
release:
  script: |
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn clean process-resources --quiet
    mvn clean versions:set "-DnewVersion=${tag}" --quiet
    git commit -am "${tag}"
    cp ../settings.xml settings.xml
    mvn clean package -Pqulice -Pzc-farm --errors --batch-mode --quiet
    git remote add heroku git@heroku.com:zerocrat.git
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git fetch
    git add settings.xml
    mvn initialize -Pshutdown --settings ../settings.xml
    git commit -m 'settings.xml' && git push -f heroku $(git symbolic-ref --short HEAD):master && git reset HEAD~1
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 https://www.0crat.com > /dev/null
  commanders:
  - yegor256
merge:
  script: |-
    mvn help:system clean install -Pqulice --settings ../settings.xml
    mvn clean site -Psite --settings ../settings.xml --quiet
    mvn clean --quiet
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders: []
architect:
- yegor256
- karato
